version: "2"
services:
  service_nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    links:
      - "service_php-fpm:service_php-fpm"
      - "service_mysql:service_mysql"
    depends_on:
      - service_php-fpm
    volumes_from:
      - service_php-fpm
  service_php-fpm:
    restart: always
    image: bitnami/php-fpm
    expose:
      - "9000"
    volumes:
      - ./conf/php/php.ini:/opt/bitnami/php/etc/php.ini
      - ./conf/php/php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ./log/php:/opt/bitnami/php/logs
      - ./www:/app
    links:
      - "service_mysql:service_mysql"
  service_mysql:
    restart: always
    image: docker.io/mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456

